// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.3
// source: api/proto/resource_manager/resource_manager.proto

// build *.pb.go from project root
// protoc -I. --go_out=plugins=grpc,paths=source_relative:. api/proto/resource_manager/*.proto

package resource_manager

import (
	context "context"
	common "github.com/dc-lab/sky/api/proto/common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                               // required
	ExecutionShellCommand    string `protobuf:"bytes,2,opt,name=execution_shell_command,json=executionShellCommand,proto3" json:"execution_shell_command,omitempty"`          // required
	RequirementsShellCommand string `protobuf:"bytes,3,opt,name=requirements_shell_command,json=requirementsShellCommand,proto3" json:"requirements_shell_command,omitempty"` // optional
}

func (x *TTask) Reset() {
	*x = TTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTask) ProtoMessage() {}

func (x *TTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTask.ProtoReflect.Descriptor instead.
func (*TTask) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{0}
}

func (x *TTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TTask) GetExecutionShellCommand() string {
	if x != nil {
		return x.ExecutionShellCommand
	}
	return ""
}

func (x *TTask) GetRequirementsShellCommand() string {
	if x != nil {
		return x.RequirementsShellCommand
	}
	return ""
}

type TGreetings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // required
}

func (x *TGreetings) Reset() {
	*x = TGreetings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGreetings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGreetings) ProtoMessage() {}

func (x *TGreetings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGreetings.ProtoReflect.Descriptor instead.
func (*TGreetings) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{1}
}

func (x *TGreetings) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type THardwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *THardwareRequest) Reset() {
	*x = THardwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *THardwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*THardwareRequest) ProtoMessage() {}

func (x *THardwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use THardwareRequest.ProtoReflect.Descriptor instead.
func (*THardwareRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{2}
}

type THardwareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalHardwareData *common.THardwareData `protobuf:"bytes,1,opt,name=total_hardware_data,json=totalHardwareData,proto3" json:"total_hardware_data,omitempty"`
	FreeHardwareData  *common.THardwareData `protobuf:"bytes,2,opt,name=free_hardware_data,json=freeHardwareData,proto3" json:"free_hardware_data,omitempty"`
}

func (x *THardwareResponse) Reset() {
	*x = THardwareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *THardwareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*THardwareResponse) ProtoMessage() {}

func (x *THardwareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use THardwareResponse.ProtoReflect.Descriptor instead.
func (*THardwareResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{3}
}

func (x *THardwareResponse) GetTotalHardwareData() *common.THardwareData {
	if x != nil {
		return x.TotalHardwareData
	}
	return nil
}

func (x *THardwareResponse) GetFreeHardwareData() *common.THardwareData {
	if x != nil {
		return x.FreeHardwareData
	}
	return nil
}

type TTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *TTask `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // required
}

func (x *TTaskRequest) Reset() {
	*x = TTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTaskRequest) ProtoMessage() {}

func (x *TTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTaskRequest.ProtoReflect.Descriptor instead.
func (*TTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{4}
}

func (x *TTaskRequest) GetTask() *TTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type TTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string          `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
	Result *common.TResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`               // required
}

func (x *TTaskResponse) Reset() {
	*x = TTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTaskResponse) ProtoMessage() {}

func (x *TTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTaskResponse.ProtoReflect.Descriptor instead.
func (*TTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{5}
}

func (x *TTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TTaskResponse) GetResult() *common.TResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type TFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                           // required
	AgentRelativeLocalPath string `protobuf:"bytes,2,opt,name=agent_relative_local_path,json=agentRelativeLocalPath,proto3" json:"agent_relative_local_path,omitempty"` // required
}

func (x *TFile) Reset() {
	*x = TFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFile) ProtoMessage() {}

func (x *TFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFile.ProtoReflect.Descriptor instead.
func (*TFile) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{6}
}

func (x *TFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TFile) GetAgentRelativeLocalPath() string {
	if x != nil {
		return x.AgentRelativeLocalPath
	}
	return ""
}

type TStageInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
	Files  []*TFile `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *TStageInRequest) Reset() {
	*x = TStageInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TStageInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TStageInRequest) ProtoMessage() {}

func (x *TStageInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TStageInRequest.ProtoReflect.Descriptor instead.
func (*TStageInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{7}
}

func (x *TStageInRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TStageInRequest) GetFiles() []*TFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type TStageInResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string          `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
	Result *common.TResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`               // required
}

func (x *TStageInResponse) Reset() {
	*x = TStageInResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TStageInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TStageInResponse) ProtoMessage() {}

func (x *TStageInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TStageInResponse.ProtoReflect.Descriptor instead.
func (*TStageInResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{8}
}

func (x *TStageInResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TStageInResponse) GetResult() *common.TResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type TStageOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
}

func (x *TStageOutRequest) Reset() {
	*x = TStageOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TStageOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TStageOutRequest) ProtoMessage() {}

func (x *TStageOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TStageOutRequest.ProtoReflect.Descriptor instead.
func (*TStageOutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{9}
}

func (x *TStageOutRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TStageOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
	TaskFiles []*TFile `protobuf:"bytes,2,rep,name=task_files,json=taskFiles,proto3" json:"task_files,omitempty"`
}

func (x *TStageOutResponse) Reset() {
	*x = TStageOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TStageOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TStageOutResponse) ProtoMessage() {}

func (x *TStageOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TStageOutResponse.ProtoReflect.Descriptor instead.
func (*TStageOutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{10}
}

func (x *TStageOutResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TStageOutResponse) GetTaskFiles() []*TFile {
	if x != nil {
		return x.TaskFiles
	}
	return nil
}

type TToAgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*TToAgentMessage_HardwareRequest
	//	*TToAgentMessage_TaskRequest
	//	*TToAgentMessage_StageInRequest
	//	*TToAgentMessage_StageOutRequest
	Body isTToAgentMessage_Body `protobuf_oneof:"Body"`
}

func (x *TToAgentMessage) Reset() {
	*x = TToAgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TToAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TToAgentMessage) ProtoMessage() {}

func (x *TToAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TToAgentMessage.ProtoReflect.Descriptor instead.
func (*TToAgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{11}
}

func (m *TToAgentMessage) GetBody() isTToAgentMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *TToAgentMessage) GetHardwareRequest() *THardwareRequest {
	if x, ok := x.GetBody().(*TToAgentMessage_HardwareRequest); ok {
		return x.HardwareRequest
	}
	return nil
}

func (x *TToAgentMessage) GetTaskRequest() *TTaskRequest {
	if x, ok := x.GetBody().(*TToAgentMessage_TaskRequest); ok {
		return x.TaskRequest
	}
	return nil
}

func (x *TToAgentMessage) GetStageInRequest() *TStageInRequest {
	if x, ok := x.GetBody().(*TToAgentMessage_StageInRequest); ok {
		return x.StageInRequest
	}
	return nil
}

func (x *TToAgentMessage) GetStageOutRequest() *TStageOutRequest {
	if x, ok := x.GetBody().(*TToAgentMessage_StageOutRequest); ok {
		return x.StageOutRequest
	}
	return nil
}

type isTToAgentMessage_Body interface {
	isTToAgentMessage_Body()
}

type TToAgentMessage_HardwareRequest struct {
	HardwareRequest *THardwareRequest `protobuf:"bytes,1,opt,name=hardware_request,json=hardwareRequest,proto3,oneof"`
}

type TToAgentMessage_TaskRequest struct {
	TaskRequest *TTaskRequest `protobuf:"bytes,2,opt,name=task_request,json=taskRequest,proto3,oneof"`
}

type TToAgentMessage_StageInRequest struct {
	StageInRequest *TStageInRequest `protobuf:"bytes,3,opt,name=stage_in_request,json=stageInRequest,proto3,oneof"`
}

type TToAgentMessage_StageOutRequest struct {
	StageOutRequest *TStageOutRequest `protobuf:"bytes,4,opt,name=stage_out_request,json=stageOutRequest,proto3,oneof"`
}

func (*TToAgentMessage_HardwareRequest) isTToAgentMessage_Body() {}

func (*TToAgentMessage_TaskRequest) isTToAgentMessage_Body() {}

func (*TToAgentMessage_StageInRequest) isTToAgentMessage_Body() {}

func (*TToAgentMessage_StageOutRequest) isTToAgentMessage_Body() {}

type TFromAgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*TFromAgentMessage_HardwareResponse
	//	*TFromAgentMessage_Greetings
	//	*TFromAgentMessage_TaskResponse
	//	*TFromAgentMessage_StageInResponse
	//	*TFromAgentMessage_StageOutResponse
	Body isTFromAgentMessage_Body `protobuf_oneof:"Body"`
}

func (x *TFromAgentMessage) Reset() {
	*x = TFromAgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFromAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFromAgentMessage) ProtoMessage() {}

func (x *TFromAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_resource_manager_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFromAgentMessage.ProtoReflect.Descriptor instead.
func (*TFromAgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP(), []int{12}
}

func (m *TFromAgentMessage) GetBody() isTFromAgentMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *TFromAgentMessage) GetHardwareResponse() *THardwareResponse {
	if x, ok := x.GetBody().(*TFromAgentMessage_HardwareResponse); ok {
		return x.HardwareResponse
	}
	return nil
}

func (x *TFromAgentMessage) GetGreetings() *TGreetings {
	if x, ok := x.GetBody().(*TFromAgentMessage_Greetings); ok {
		return x.Greetings
	}
	return nil
}

func (x *TFromAgentMessage) GetTaskResponse() *TTaskResponse {
	if x, ok := x.GetBody().(*TFromAgentMessage_TaskResponse); ok {
		return x.TaskResponse
	}
	return nil
}

func (x *TFromAgentMessage) GetStageInResponse() *TStageInResponse {
	if x, ok := x.GetBody().(*TFromAgentMessage_StageInResponse); ok {
		return x.StageInResponse
	}
	return nil
}

func (x *TFromAgentMessage) GetStageOutResponse() *TStageOutResponse {
	if x, ok := x.GetBody().(*TFromAgentMessage_StageOutResponse); ok {
		return x.StageOutResponse
	}
	return nil
}

type isTFromAgentMessage_Body interface {
	isTFromAgentMessage_Body()
}

type TFromAgentMessage_HardwareResponse struct {
	HardwareResponse *THardwareResponse `protobuf:"bytes,1,opt,name=hardware_response,json=hardwareResponse,proto3,oneof"`
}

type TFromAgentMessage_Greetings struct {
	Greetings *TGreetings `protobuf:"bytes,2,opt,name=greetings,proto3,oneof"`
}

type TFromAgentMessage_TaskResponse struct {
	TaskResponse *TTaskResponse `protobuf:"bytes,3,opt,name=task_response,json=taskResponse,proto3,oneof"`
}

type TFromAgentMessage_StageInResponse struct {
	StageInResponse *TStageInResponse `protobuf:"bytes,4,opt,name=stage_in_response,json=stageInResponse,proto3,oneof"`
}

type TFromAgentMessage_StageOutResponse struct {
	StageOutResponse *TStageOutResponse `protobuf:"bytes,5,opt,name=stage_out_response,json=stageOutResponse,proto3,oneof"`
}

func (*TFromAgentMessage_HardwareResponse) isTFromAgentMessage_Body() {}

func (*TFromAgentMessage_Greetings) isTFromAgentMessage_Body() {}

func (*TFromAgentMessage_TaskResponse) isTFromAgentMessage_Body() {}

func (*TFromAgentMessage_StageInResponse) isTFromAgentMessage_Body() {}

func (*TFromAgentMessage_StageOutResponse) isTFromAgentMessage_Body() {}

var File_api_proto_resource_manager_resource_manager_proto protoreflect.FileDescriptor

var file_api_proto_resource_manager_resource_manager_proto_rawDesc = []byte{
	0x0a, 0x31, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x05, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a,
	0x17, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3c, 0x0a, 0x1a, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x22, 0x22, 0x0a, 0x0a, 0x54, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x54, 0x48, 0x61, 0x72, 0x64,
	0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x11,
	0x54, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x45, 0x0a, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x68, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x48, 0x61, 0x72, 0x64,
	0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x43, 0x0a, 0x12, 0x66, 0x72, 0x65, 0x65,
	0x5f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x10, 0x66, 0x72, 0x65,
	0x65, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3b, 0x0a,
	0x0c, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x51, 0x0a, 0x0d, 0x54, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x52, 0x0a,
	0x05, 0x54, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x19, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x59, 0x0a, 0x0f, 0x54, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x2d, 0x0a,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x54, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x10,
	0x54, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x54, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x2b, 0x0a, 0x10, 0x54, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22,
	0x64, 0x0a, 0x11, 0x54, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x36, 0x0a,
	0x0a, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x09, 0x74, 0x61, 0x73, 0x6b,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xd0, 0x02, 0x0a, 0x0f, 0x54, 0x54, 0x6f, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4f, 0x0a, 0x10, 0x68, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x68, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0c, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x4d, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50,
	0x0a, 0x11, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x9c, 0x03, 0x0a, 0x11, 0x54, 0x46, 0x72,
	0x6f, 0x6d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x52,
	0x0a, 0x11, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x48, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x10, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x48, 0x00, 0x52, 0x09, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x46, 0x0a, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x74, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x32, 0x67, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x54, 0x0a, 0x04, 0x53, 0x65,
	0x6e, 0x64, 0x12, 0x23, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x21, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x54, 0x6f, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x63, 0x2d, 0x6c, 0x61, 0x62, 0x2f, 0x73, 0x6b, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_resource_manager_resource_manager_proto_rawDescOnce sync.Once
	file_api_proto_resource_manager_resource_manager_proto_rawDescData = file_api_proto_resource_manager_resource_manager_proto_rawDesc
)

func file_api_proto_resource_manager_resource_manager_proto_rawDescGZIP() []byte {
	file_api_proto_resource_manager_resource_manager_proto_rawDescOnce.Do(func() {
		file_api_proto_resource_manager_resource_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_resource_manager_resource_manager_proto_rawDescData)
	})
	return file_api_proto_resource_manager_resource_manager_proto_rawDescData
}

var file_api_proto_resource_manager_resource_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_resource_manager_resource_manager_proto_goTypes = []interface{}{
	(*TTask)(nil),                // 0: resource_manager.TTask
	(*TGreetings)(nil),           // 1: resource_manager.TGreetings
	(*THardwareRequest)(nil),     // 2: resource_manager.THardwareRequest
	(*THardwareResponse)(nil),    // 3: resource_manager.THardwareResponse
	(*TTaskRequest)(nil),         // 4: resource_manager.TTaskRequest
	(*TTaskResponse)(nil),        // 5: resource_manager.TTaskResponse
	(*TFile)(nil),                // 6: resource_manager.TFile
	(*TStageInRequest)(nil),      // 7: resource_manager.TStageInRequest
	(*TStageInResponse)(nil),     // 8: resource_manager.TStageInResponse
	(*TStageOutRequest)(nil),     // 9: resource_manager.TStageOutRequest
	(*TStageOutResponse)(nil),    // 10: resource_manager.TStageOutResponse
	(*TToAgentMessage)(nil),      // 11: resource_manager.TToAgentMessage
	(*TFromAgentMessage)(nil),    // 12: resource_manager.TFromAgentMessage
	(*common.THardwareData)(nil), // 13: entity.THardwareData
	(*common.TResult)(nil),       // 14: action.TResult
}
var file_api_proto_resource_manager_resource_manager_proto_depIdxs = []int32{
	13, // 0: resource_manager.THardwareResponse.total_hardware_data:type_name -> entity.THardwareData
	13, // 1: resource_manager.THardwareResponse.free_hardware_data:type_name -> entity.THardwareData
	0,  // 2: resource_manager.TTaskRequest.task:type_name -> resource_manager.TTask
	14, // 3: resource_manager.TTaskResponse.result:type_name -> action.TResult
	6,  // 4: resource_manager.TStageInRequest.files:type_name -> resource_manager.TFile
	14, // 5: resource_manager.TStageInResponse.result:type_name -> action.TResult
	6,  // 6: resource_manager.TStageOutResponse.task_files:type_name -> resource_manager.TFile
	2,  // 7: resource_manager.TToAgentMessage.hardware_request:type_name -> resource_manager.THardwareRequest
	4,  // 8: resource_manager.TToAgentMessage.task_request:type_name -> resource_manager.TTaskRequest
	7,  // 9: resource_manager.TToAgentMessage.stage_in_request:type_name -> resource_manager.TStageInRequest
	9,  // 10: resource_manager.TToAgentMessage.stage_out_request:type_name -> resource_manager.TStageOutRequest
	3,  // 11: resource_manager.TFromAgentMessage.hardware_response:type_name -> resource_manager.THardwareResponse
	1,  // 12: resource_manager.TFromAgentMessage.greetings:type_name -> resource_manager.TGreetings
	5,  // 13: resource_manager.TFromAgentMessage.task_response:type_name -> resource_manager.TTaskResponse
	8,  // 14: resource_manager.TFromAgentMessage.stage_in_response:type_name -> resource_manager.TStageInResponse
	10, // 15: resource_manager.TFromAgentMessage.stage_out_response:type_name -> resource_manager.TStageOutResponse
	12, // 16: resource_manager.ResourceManager.Send:input_type -> resource_manager.TFromAgentMessage
	11, // 17: resource_manager.ResourceManager.Send:output_type -> resource_manager.TToAgentMessage
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_resource_manager_resource_manager_proto_init() }
func file_api_proto_resource_manager_resource_manager_proto_init() {
	if File_api_proto_resource_manager_resource_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGreetings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*THardwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*THardwareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TStageInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TStageInResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TStageOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TStageOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TToAgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_resource_manager_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFromAgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_resource_manager_resource_manager_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*TToAgentMessage_HardwareRequest)(nil),
		(*TToAgentMessage_TaskRequest)(nil),
		(*TToAgentMessage_StageInRequest)(nil),
		(*TToAgentMessage_StageOutRequest)(nil),
	}
	file_api_proto_resource_manager_resource_manager_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*TFromAgentMessage_HardwareResponse)(nil),
		(*TFromAgentMessage_Greetings)(nil),
		(*TFromAgentMessage_TaskResponse)(nil),
		(*TFromAgentMessage_StageInResponse)(nil),
		(*TFromAgentMessage_StageOutResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_resource_manager_resource_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_resource_manager_resource_manager_proto_goTypes,
		DependencyIndexes: file_api_proto_resource_manager_resource_manager_proto_depIdxs,
		MessageInfos:      file_api_proto_resource_manager_resource_manager_proto_msgTypes,
	}.Build()
	File_api_proto_resource_manager_resource_manager_proto = out.File
	file_api_proto_resource_manager_resource_manager_proto_rawDesc = nil
	file_api_proto_resource_manager_resource_manager_proto_goTypes = nil
	file_api_proto_resource_manager_resource_manager_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceManagerClient is the client API for ResourceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceManagerClient interface {
	Send(ctx context.Context, opts ...grpc.CallOption) (ResourceManager_SendClient, error)
}

type resourceManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceManagerClient(cc grpc.ClientConnInterface) ResourceManagerClient {
	return &resourceManagerClient{cc}
}

func (c *resourceManagerClient) Send(ctx context.Context, opts ...grpc.CallOption) (ResourceManager_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ResourceManager_serviceDesc.Streams[0], "/resource_manager.ResourceManager/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceManagerSendClient{stream}
	return x, nil
}

type ResourceManager_SendClient interface {
	Send(*TFromAgentMessage) error
	Recv() (*TToAgentMessage, error)
	grpc.ClientStream
}

type resourceManagerSendClient struct {
	grpc.ClientStream
}

func (x *resourceManagerSendClient) Send(m *TFromAgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resourceManagerSendClient) Recv() (*TToAgentMessage, error) {
	m := new(TToAgentMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResourceManagerServer is the server API for ResourceManager service.
type ResourceManagerServer interface {
	Send(ResourceManager_SendServer) error
}

// UnimplementedResourceManagerServer can be embedded to have forward compatible implementations.
type UnimplementedResourceManagerServer struct {
}

func (*UnimplementedResourceManagerServer) Send(ResourceManager_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterResourceManagerServer(s *grpc.Server, srv ResourceManagerServer) {
	s.RegisterService(&_ResourceManager_serviceDesc, srv)
}

func _ResourceManager_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResourceManagerServer).Send(&resourceManagerSendServer{stream})
}

type ResourceManager_SendServer interface {
	Send(*TToAgentMessage) error
	Recv() (*TFromAgentMessage, error)
	grpc.ServerStream
}

type resourceManagerSendServer struct {
	grpc.ServerStream
}

func (x *resourceManagerSendServer) Send(m *TToAgentMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resourceManagerSendServer) Recv() (*TFromAgentMessage, error) {
	m := new(TFromAgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ResourceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource_manager.ResourceManager",
	HandlerType: (*ResourceManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _ResourceManager_Send_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/resource_manager/resource_manager.proto",
}
