// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.3
// source: protos/agent.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TResult_TResultCode int32

const (
	TResult_NONE    TResult_TResultCode = 0
	TResult_WAIT    TResult_TResultCode = 1
	TResult_RUN     TResult_TResultCode = 2
	TResult_FAILED  TResult_TResultCode = 3
	TResult_SUCCESS TResult_TResultCode = 4
)

// Enum value maps for TResult_TResultCode.
var (
	TResult_TResultCode_name = map[int32]string{
		0: "NONE",
		1: "WAIT",
		2: "RUN",
		3: "FAILED",
		4: "SUCCESS",
	}
	TResult_TResultCode_value = map[string]int32{
		"NONE":    0,
		"WAIT":    1,
		"RUN":     2,
		"FAILED":  3,
		"SUCCESS": 4,
	}
)

func (x TResult_TResultCode) Enum() *TResult_TResultCode {
	p := new(TResult_TResultCode)
	*p = x
	return p
}

func (x TResult_TResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TResult_TResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_agent_proto_enumTypes[0].Descriptor()
}

func (TResult_TResultCode) Type() protoreflect.EnumType {
	return &file_protos_agent_proto_enumTypes[0]
}

func (x TResult_TResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TResult_TResultCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TResult_TResultCode(num)
	return nil
}

// Deprecated: Use TResult_TResultCode.Descriptor instead.
func (TResult_TResultCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{10, 0}
}

type TResult_TErrorCode int32

const (
	TResult_UNKNOWN          TResult_TErrorCode = 0
	TResult_INTERNAL         TResult_TErrorCode = 1
	TResult_INVALID_ARGUMENT TResult_TErrorCode = 2
	TResult_UNAUTHENTICATED  TResult_TErrorCode = 3
	TResult_UNAUTHORIZED     TResult_TErrorCode = 4
)

// Enum value maps for TResult_TErrorCode.
var (
	TResult_TErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INTERNAL",
		2: "INVALID_ARGUMENT",
		3: "UNAUTHENTICATED",
		4: "UNAUTHORIZED",
	}
	TResult_TErrorCode_value = map[string]int32{
		"UNKNOWN":          0,
		"INTERNAL":         1,
		"INVALID_ARGUMENT": 2,
		"UNAUTHENTICATED":  3,
		"UNAUTHORIZED":     4,
	}
)

func (x TResult_TErrorCode) Enum() *TResult_TErrorCode {
	p := new(TResult_TErrorCode)
	*p = x
	return p
}

func (x TResult_TErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TResult_TErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_agent_proto_enumTypes[1].Descriptor()
}

func (TResult_TErrorCode) Type() protoreflect.EnumType {
	return &file_protos_agent_proto_enumTypes[1]
}

func (x TResult_TErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TResult_TErrorCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TResult_TErrorCode(num)
	return nil
}

// Deprecated: Use TResult_TErrorCode.Descriptor instead.
func (TResult_TErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{10, 1}
}

type TTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	ExecutionShellCommand    *string `protobuf:"bytes,2,req,name=execution_shell_command,json=executionShellCommand" json:"execution_shell_command,omitempty"`
	RequirementsShellCommand *string `protobuf:"bytes,3,opt,name=requirements_shell_command,json=requirementsShellCommand" json:"requirements_shell_command,omitempty"`
}

func (x *TTask) Reset() {
	*x = TTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTask) ProtoMessage() {}

func (x *TTask) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTask.ProtoReflect.Descriptor instead.
func (*TTask) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TTask) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *TTask) GetExecutionShellCommand() string {
	if x != nil && x.ExecutionShellCommand != nil {
		return *x.ExecutionShellCommand
	}
	return ""
}

func (x *TTask) GetRequirementsShellCommand() string {
	if x != nil && x.RequirementsShellCommand != nil {
		return *x.RequirementsShellCommand
	}
	return ""
}

type THardwareData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoresCount   *int32  `protobuf:"varint,1,req,name=cores_count,json=coresCount" json:"cores_count,omitempty"`
	MemoryAmount *uint64 `protobuf:"varint,2,req,name=memory_amount,json=memoryAmount" json:"memory_amount,omitempty"`
	DiskAmount   *uint64 `protobuf:"varint,3,req,name=disk_amount,json=diskAmount" json:"disk_amount,omitempty"`
}

func (x *THardwareData) Reset() {
	*x = THardwareData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *THardwareData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*THardwareData) ProtoMessage() {}

func (x *THardwareData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use THardwareData.ProtoReflect.Descriptor instead.
func (*THardwareData) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{1}
}

func (x *THardwareData) GetCoresCount() int32 {
	if x != nil && x.CoresCount != nil {
		return *x.CoresCount
	}
	return 0
}

func (x *THardwareData) GetMemoryAmount() uint64 {
	if x != nil && x.MemoryAmount != nil {
		return *x.MemoryAmount
	}
	return 0
}

func (x *THardwareData) GetDiskAmount() uint64 {
	if x != nil && x.DiskAmount != nil {
		return *x.DiskAmount
	}
	return 0
}

type TGreetings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *TGreetings) Reset() {
	*x = TGreetings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TGreetings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGreetings) ProtoMessage() {}

func (x *TGreetings) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGreetings.ProtoReflect.Descriptor instead.
func (*TGreetings) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TGreetings) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type THardwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *THardwareRequest) Reset() {
	*x = THardwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *THardwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*THardwareRequest) ProtoMessage() {}

func (x *THardwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use THardwareRequest.ProtoReflect.Descriptor instead.
func (*THardwareRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{3}
}

type TTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *TTask `protobuf:"bytes,1,req,name=task" json:"task,omitempty"`
}

func (x *TTaskRequest) Reset() {
	*x = TTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTaskRequest) ProtoMessage() {}

func (x *TTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTaskRequest.ProtoReflect.Descriptor instead.
func (*TTaskRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TTaskRequest) GetTask() *TTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type TTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId *string  `protobuf:"bytes,1,req,name=task_id,json=taskId" json:"task_id,omitempty"`
	Result *TResult `protobuf:"bytes,2,req,name=result" json:"result,omitempty"`
}

func (x *TTaskResponse) Reset() {
	*x = TTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTaskResponse) ProtoMessage() {}

func (x *TTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTaskResponse.ProtoReflect.Descriptor instead.
func (*TTaskResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{5}
}

func (x *TTaskResponse) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *TTaskResponse) GetResult() *TResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type TFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                     *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	AgentRelativeLocalPath *string `protobuf:"bytes,2,req,name=agent_relative_local_path,json=agentRelativeLocalPath" json:"agent_relative_local_path,omitempty"`
}

func (x *TFile) Reset() {
	*x = TFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFile) ProtoMessage() {}

func (x *TFile) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFile.ProtoReflect.Descriptor instead.
func (*TFile) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TFile) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *TFile) GetAgentRelativeLocalPath() string {
	if x != nil && x.AgentRelativeLocalPath != nil {
		return *x.AgentRelativeLocalPath
	}
	return ""
}

type TStageIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId *string  `protobuf:"bytes,1,req,name=task_id,json=taskId" json:"task_id,omitempty"`
	Files  []*TFile `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
}

func (x *TStageIn) Reset() {
	*x = TStageIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TStageIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TStageIn) ProtoMessage() {}

func (x *TStageIn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TStageIn.ProtoReflect.Descriptor instead.
func (*TStageIn) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TStageIn) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *TStageIn) GetFiles() []*TFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type TToAgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*TToAgentMessage_HardwareRequest
	//	*TToAgentMessage_TaskRequest
	//	*TToAgentMessage_StageInRequest
	Body isTToAgentMessage_Body `protobuf_oneof:"Body"`
}

func (x *TToAgentMessage) Reset() {
	*x = TToAgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TToAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TToAgentMessage) ProtoMessage() {}

func (x *TToAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TToAgentMessage.ProtoReflect.Descriptor instead.
func (*TToAgentMessage) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{8}
}

func (m *TToAgentMessage) GetBody() isTToAgentMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *TToAgentMessage) GetHardwareRequest() *THardwareRequest {
	if x, ok := x.GetBody().(*TToAgentMessage_HardwareRequest); ok {
		return x.HardwareRequest
	}
	return nil
}

func (x *TToAgentMessage) GetTaskRequest() *TTaskRequest {
	if x, ok := x.GetBody().(*TToAgentMessage_TaskRequest); ok {
		return x.TaskRequest
	}
	return nil
}

func (x *TToAgentMessage) GetStageInRequest() *TStageIn {
	if x, ok := x.GetBody().(*TToAgentMessage_StageInRequest); ok {
		return x.StageInRequest
	}
	return nil
}

type isTToAgentMessage_Body interface {
	isTToAgentMessage_Body()
}

type TToAgentMessage_HardwareRequest struct {
	HardwareRequest *THardwareRequest `protobuf:"bytes,1,opt,name=hardware_request,json=hardwareRequest,oneof"`
}

type TToAgentMessage_TaskRequest struct {
	TaskRequest *TTaskRequest `protobuf:"bytes,2,opt,name=task_request,json=taskRequest,oneof"`
}

type TToAgentMessage_StageInRequest struct {
	StageInRequest *TStageIn `protobuf:"bytes,3,opt,name=stage_in_request,json=stageInRequest,oneof"`
}

func (*TToAgentMessage_HardwareRequest) isTToAgentMessage_Body() {}

func (*TToAgentMessage_TaskRequest) isTToAgentMessage_Body() {}

func (*TToAgentMessage_StageInRequest) isTToAgentMessage_Body() {}

type TFromAgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*TFromAgentMessage_HardwareData
	//	*TFromAgentMessage_Greetings
	//	*TFromAgentMessage_TaskResponse
	Body isTFromAgentMessage_Body `protobuf_oneof:"Body"`
}

func (x *TFromAgentMessage) Reset() {
	*x = TFromAgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFromAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFromAgentMessage) ProtoMessage() {}

func (x *TFromAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFromAgentMessage.ProtoReflect.Descriptor instead.
func (*TFromAgentMessage) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{9}
}

func (m *TFromAgentMessage) GetBody() isTFromAgentMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *TFromAgentMessage) GetHardwareData() *THardwareData {
	if x, ok := x.GetBody().(*TFromAgentMessage_HardwareData); ok {
		return x.HardwareData
	}
	return nil
}

func (x *TFromAgentMessage) GetGreetings() *TGreetings {
	if x, ok := x.GetBody().(*TFromAgentMessage_Greetings); ok {
		return x.Greetings
	}
	return nil
}

func (x *TFromAgentMessage) GetTaskResponse() *TTaskResponse {
	if x, ok := x.GetBody().(*TFromAgentMessage_TaskResponse); ok {
		return x.TaskResponse
	}
	return nil
}

type isTFromAgentMessage_Body interface {
	isTFromAgentMessage_Body()
}

type TFromAgentMessage_HardwareData struct {
	HardwareData *THardwareData `protobuf:"bytes,1,opt,name=hardware_data,json=hardwareData,oneof"`
}

type TFromAgentMessage_Greetings struct {
	Greetings *TGreetings `protobuf:"bytes,2,opt,name=greetings,oneof"`
}

type TFromAgentMessage_TaskResponse struct {
	TaskResponse *TTaskResponse `protobuf:"bytes,3,opt,name=task_response,json=taskResponse,oneof"`
}

func (*TFromAgentMessage_HardwareData) isTFromAgentMessage_Body() {}

func (*TFromAgentMessage_Greetings) isTFromAgentMessage_Body() {}

func (*TFromAgentMessage_TaskResponse) isTFromAgentMessage_Body() {}

type TResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode *TResult_TResultCode `protobuf:"varint,1,req,name=result_code,json=resultCode,enum=protobuf.TResult_TResultCode" json:"result_code,omitempty"`
	ErrorCode  *TResult_TErrorCode  `protobuf:"varint,2,opt,name=error_code,json=errorCode,enum=protobuf.TResult_TErrorCode" json:"error_code,omitempty"`
}

func (x *TResult) Reset() {
	*x = TResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TResult) ProtoMessage() {}

func (x *TResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TResult.ProtoReflect.Descriptor instead.
func (*TResult) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{10}
}

func (x *TResult) GetResultCode() TResult_TResultCode {
	if x != nil && x.ResultCode != nil {
		return *x.ResultCode
	}
	return TResult_NONE
}

func (x *TResult) GetErrorCode() TResult_TErrorCode {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return TResult_UNKNOWN
}

var File_protos_agent_proto protoreflect.FileDescriptor

var file_protos_agent_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x8d,
	0x01, 0x0a, 0x05, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x15, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x3c, 0x0a, 0x1a, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x76,
	0x0a, 0x0d, 0x54, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x04, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x6b,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x0a, 0x54, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x54, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x33,
	0x0a, 0x0c, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74,
	0x61, 0x73, 0x6b, 0x22, 0x53, 0x0a, 0x0d, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x29, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x52, 0x0a, 0x05, 0x54, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x39, 0x0a, 0x19, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x16, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x22, 0x4a, 0x0a, 0x08,
	0x54, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xdf, 0x01, 0x0a, 0x0f, 0x54, 0x54, 0x6f,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x47, 0x0a, 0x10,
	0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3e, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x48, 0x00, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0xd1, 0x01, 0x0a, 0x11, 0x54,
	0x46, 0x72, 0x6f, 0x6d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x3e, 0x0a, 0x0d, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x0c, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x34, 0x0a, 0x09, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x00, 0x52, 0x09, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x3e, 0x0a, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0xb1,
	0x02, 0x0a, 0x07, 0x54, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3e, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2e, 0x54, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x54, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x43, 0x0a, 0x0b, 0x54, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x49, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x55,
	0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x04, 0x22, 0x64, 0x0a, 0x0a,
	0x54, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x55,
	0x4e, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44,
	0x10, 0x04, 0x32, 0x57, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x54, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
}

var (
	file_protos_agent_proto_rawDescOnce sync.Once
	file_protos_agent_proto_rawDescData = file_protos_agent_proto_rawDesc
)

func file_protos_agent_proto_rawDescGZIP() []byte {
	file_protos_agent_proto_rawDescOnce.Do(func() {
		file_protos_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_agent_proto_rawDescData)
	})
	return file_protos_agent_proto_rawDescData
}

var file_protos_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_agent_proto_goTypes = []interface{}{
	(TResult_TResultCode)(0),  // 0: protobuf.TResult.TResultCode
	(TResult_TErrorCode)(0),   // 1: protobuf.TResult.TErrorCode
	(*TTask)(nil),             // 2: protobuf.TTask
	(*THardwareData)(nil),     // 3: protobuf.THardwareData
	(*TGreetings)(nil),        // 4: protobuf.TGreetings
	(*THardwareRequest)(nil),  // 5: protobuf.THardwareRequest
	(*TTaskRequest)(nil),      // 6: protobuf.TTaskRequest
	(*TTaskResponse)(nil),     // 7: protobuf.TTaskResponse
	(*TFile)(nil),             // 8: protobuf.TFile
	(*TStageIn)(nil),          // 9: protobuf.TStageIn
	(*TToAgentMessage)(nil),   // 10: protobuf.TToAgentMessage
	(*TFromAgentMessage)(nil), // 11: protobuf.TFromAgentMessage
	(*TResult)(nil),           // 12: protobuf.TResult
}
var file_protos_agent_proto_depIdxs = []int32{
	2,  // 0: protobuf.TTaskRequest.task:type_name -> protobuf.TTask
	12, // 1: protobuf.TTaskResponse.result:type_name -> protobuf.TResult
	8,  // 2: protobuf.TStageIn.files:type_name -> protobuf.TFile
	5,  // 3: protobuf.TToAgentMessage.hardware_request:type_name -> protobuf.THardwareRequest
	6,  // 4: protobuf.TToAgentMessage.task_request:type_name -> protobuf.TTaskRequest
	9,  // 5: protobuf.TToAgentMessage.stage_in_request:type_name -> protobuf.TStageIn
	3,  // 6: protobuf.TFromAgentMessage.hardware_data:type_name -> protobuf.THardwareData
	4,  // 7: protobuf.TFromAgentMessage.greetings:type_name -> protobuf.TGreetings
	7,  // 8: protobuf.TFromAgentMessage.task_response:type_name -> protobuf.TTaskResponse
	0,  // 9: protobuf.TResult.result_code:type_name -> protobuf.TResult.TResultCode
	1,  // 10: protobuf.TResult.error_code:type_name -> protobuf.TResult.TErrorCode
	11, // 11: protobuf.ResourceManager.Send:input_type -> protobuf.TFromAgentMessage
	10, // 12: protobuf.ResourceManager.Send:output_type -> protobuf.TToAgentMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protos_agent_proto_init() }
func file_protos_agent_proto_init() {
	if File_protos_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*THardwareData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TGreetings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*THardwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TStageIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TToAgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFromAgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_agent_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*TToAgentMessage_HardwareRequest)(nil),
		(*TToAgentMessage_TaskRequest)(nil),
		(*TToAgentMessage_StageInRequest)(nil),
	}
	file_protos_agent_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*TFromAgentMessage_HardwareData)(nil),
		(*TFromAgentMessage_Greetings)(nil),
		(*TFromAgentMessage_TaskResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_agent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_agent_proto_goTypes,
		DependencyIndexes: file_protos_agent_proto_depIdxs,
		EnumInfos:         file_protos_agent_proto_enumTypes,
		MessageInfos:      file_protos_agent_proto_msgTypes,
	}.Build()
	File_protos_agent_proto = out.File
	file_protos_agent_proto_rawDesc = nil
	file_protos_agent_proto_goTypes = nil
	file_protos_agent_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceManagerClient is the client API for ResourceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceManagerClient interface {
	Send(ctx context.Context, opts ...grpc.CallOption) (ResourceManager_SendClient, error)
}

type resourceManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceManagerClient(cc grpc.ClientConnInterface) ResourceManagerClient {
	return &resourceManagerClient{cc}
}

func (c *resourceManagerClient) Send(ctx context.Context, opts ...grpc.CallOption) (ResourceManager_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ResourceManager_serviceDesc.Streams[0], "/protobuf.ResourceManager/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceManagerSendClient{stream}
	return x, nil
}

type ResourceManager_SendClient interface {
	Send(*TFromAgentMessage) error
	Recv() (*TToAgentMessage, error)
	grpc.ClientStream
}

type resourceManagerSendClient struct {
	grpc.ClientStream
}

func (x *resourceManagerSendClient) Send(m *TFromAgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resourceManagerSendClient) Recv() (*TToAgentMessage, error) {
	m := new(TToAgentMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResourceManagerServer is the server API for ResourceManager service.
type ResourceManagerServer interface {
	Send(ResourceManager_SendServer) error
}

// UnimplementedResourceManagerServer can be embedded to have forward compatible implementations.
type UnimplementedResourceManagerServer struct {
}

func (*UnimplementedResourceManagerServer) Send(ResourceManager_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterResourceManagerServer(s *grpc.Server, srv ResourceManagerServer) {
	s.RegisterService(&_ResourceManager_serviceDesc, srv)
}

func _ResourceManager_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResourceManagerServer).Send(&resourceManagerSendServer{stream})
}

type ResourceManager_SendServer interface {
	Send(*TToAgentMessage) error
	Recv() (*TFromAgentMessage, error)
	grpc.ServerStream
}

type resourceManagerSendServer struct {
	grpc.ServerStream
}

func (x *resourceManagerSendServer) Send(m *TToAgentMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resourceManagerSendServer) Recv() (*TFromAgentMessage, error) {
	m := new(TFromAgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ResourceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ResourceManager",
	HandlerType: (*ResourceManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _ResourceManager_Send_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/agent.proto",
}
