Endpoints:
  - PathPattern: "/login"
    Hostname: "localhost:6272"
    AuthOptional: true
  - PathPattern: "/register"
    Hostname: "localhost:6272"
    AuthOptional: true
  - PathPattern: "/change_password"
    Hostname: "localhost:6272"
  - PathPattern: "/groups"
    Hostname: "localhost:6272"
  - PathPattern: "/resource"
    Hostname: "localhost:8090"
