// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: api/proto/common/action.proto

// build *.pb.go from project root
// protoc -I. --go_out=plugins=grpc,paths=source_relative:. api/proto/common/*.proto

package common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TResult_TResultCode int32

const (
	TResult_NONE    TResult_TResultCode = 0
	TResult_WAIT    TResult_TResultCode = 1
	TResult_RUN     TResult_TResultCode = 2
	TResult_FAILED  TResult_TResultCode = 3
	TResult_SUCCESS TResult_TResultCode = 4
)

// Enum value maps for TResult_TResultCode.
var (
	TResult_TResultCode_name = map[int32]string{
		0: "NONE",
		1: "WAIT",
		2: "RUN",
		3: "FAILED",
		4: "SUCCESS",
	}
	TResult_TResultCode_value = map[string]int32{
		"NONE":    0,
		"WAIT":    1,
		"RUN":     2,
		"FAILED":  3,
		"SUCCESS": 4,
	}
)

func (x TResult_TResultCode) Enum() *TResult_TResultCode {
	p := new(TResult_TResultCode)
	*p = x
	return p
}

func (x TResult_TResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TResult_TResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_action_proto_enumTypes[0].Descriptor()
}

func (TResult_TResultCode) Type() protoreflect.EnumType {
	return &file_api_proto_common_action_proto_enumTypes[0]
}

func (x TResult_TResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TResult_TResultCode.Descriptor instead.
func (TResult_TResultCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_action_proto_rawDescGZIP(), []int{0, 0}
}

type TResult_TErrorCode int32

const (
	TResult_UNKNOWN          TResult_TErrorCode = 0
	TResult_INTERNAL         TResult_TErrorCode = 1
	TResult_INVALID_ARGUMENT TResult_TErrorCode = 2
	TResult_UNAUTHENTICATED  TResult_TErrorCode = 3
	TResult_UNAUTHORIZED     TResult_TErrorCode = 4
	TResult_NOT_IMPLEMENTED  TResult_TErrorCode = 5
)

// Enum value maps for TResult_TErrorCode.
var (
	TResult_TErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INTERNAL",
		2: "INVALID_ARGUMENT",
		3: "UNAUTHENTICATED",
		4: "UNAUTHORIZED",
		5: "NOT_IMPLEMENTED",
	}
	TResult_TErrorCode_value = map[string]int32{
		"UNKNOWN":          0,
		"INTERNAL":         1,
		"INVALID_ARGUMENT": 2,
		"UNAUTHENTICATED":  3,
		"UNAUTHORIZED":     4,
		"NOT_IMPLEMENTED":  5,
	}
)

func (x TResult_TErrorCode) Enum() *TResult_TErrorCode {
	p := new(TResult_TErrorCode)
	*p = x
	return p
}

func (x TResult_TErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TResult_TErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_action_proto_enumTypes[1].Descriptor()
}

func (TResult_TErrorCode) Type() protoreflect.EnumType {
	return &file_api_proto_common_action_proto_enumTypes[1]
}

func (x TResult_TErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TResult_TErrorCode.Descriptor instead.
func (TResult_TErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_action_proto_rawDescGZIP(), []int{0, 1}
}

type TResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode TResult_TResultCode `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=action.TResult_TResultCode" json:"result_code,omitempty"` // required
	ErrorCode  TResult_TErrorCode  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=action.TResult_TErrorCode" json:"error_code,omitempty"`     // optional
}

func (x *TResult) Reset() {
	*x = TResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_common_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TResult) ProtoMessage() {}

func (x *TResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TResult.ProtoReflect.Descriptor instead.
func (*TResult) Descriptor() ([]byte, []int) {
	return file_api_proto_common_action_proto_rawDescGZIP(), []int{0}
}

func (x *TResult) GetResultCode() TResult_TResultCode {
	if x != nil {
		return x.ResultCode
	}
	return TResult_NONE
}

func (x *TResult) GetErrorCode() TResult_TErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return TResult_UNKNOWN
}

var File_api_proto_common_action_proto protoreflect.FileDescriptor

var file_api_proto_common_action_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc2, 0x02, 0x0a, 0x07, 0x54, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x54, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x54, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x54, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x43, 0x0a, 0x0b,
	0x54, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x49, 0x54, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x52, 0x55, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x04, 0x22, 0x79, 0x0a, 0x0a, 0x54, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x02,
	0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41,
	0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f,
	0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x4f, 0x54, 0x5f, 0x49,
	0x4d, 0x50, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x05, 0x42, 0x28, 0x5a, 0x26,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x63, 0x2d, 0x6c, 0x61,
	0x62, 0x2f, 0x73, 0x6b, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_common_action_proto_rawDescOnce sync.Once
	file_api_proto_common_action_proto_rawDescData = file_api_proto_common_action_proto_rawDesc
)

func file_api_proto_common_action_proto_rawDescGZIP() []byte {
	file_api_proto_common_action_proto_rawDescOnce.Do(func() {
		file_api_proto_common_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_common_action_proto_rawDescData)
	})
	return file_api_proto_common_action_proto_rawDescData
}

var file_api_proto_common_action_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_common_action_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_common_action_proto_goTypes = []interface{}{
	(TResult_TResultCode)(0), // 0: action.TResult.TResultCode
	(TResult_TErrorCode)(0),  // 1: action.TResult.TErrorCode
	(*TResult)(nil),          // 2: action.TResult
}
var file_api_proto_common_action_proto_depIdxs = []int32{
	0, // 0: action.TResult.result_code:type_name -> action.TResult.TResultCode
	1, // 1: action.TResult.error_code:type_name -> action.TResult.TErrorCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_common_action_proto_init() }
func file_api_proto_common_action_proto_init() {
	if File_api_proto_common_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_common_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_common_action_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_action_proto_goTypes,
		DependencyIndexes: file_api_proto_common_action_proto_depIdxs,
		EnumInfos:         file_api_proto_common_action_proto_enumTypes,
		MessageInfos:      file_api_proto_common_action_proto_msgTypes,
	}.Build()
	File_api_proto_common_action_proto = out.File
	file_api_proto_common_action_proto_rawDesc = nil
	file_api_proto_common_action_proto_goTypes = nil
	file_api_proto_common_action_proto_depIdxs = nil
}
