// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: api/proto/resource_manager.proto

// build *.pb.go from project root
// protoc -I. --go_out=plugins=grpc,paths=source_relative:. api/proto/resource_manager/*.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EResourceType int32

const (
	EResourceType_RESOURCE_UNKNOWN EResourceType = 0
	EResourceType_SINGLE           EResourceType = 1
	EResourceType_POOL             EResourceType = 2
	EResourceType_CLOUD_INSTANCE   EResourceType = 3
	EResourceType_CLOUD_TASK       EResourceType = 4
)

// Enum value maps for EResourceType.
var (
	EResourceType_name = map[int32]string{
		0: "RESOURCE_UNKNOWN",
		1: "SINGLE",
		2: "POOL",
		3: "CLOUD_INSTANCE",
		4: "CLOUD_TASK",
	}
	EResourceType_value = map[string]int32{
		"RESOURCE_UNKNOWN": 0,
		"SINGLE":           1,
		"POOL":             2,
		"CLOUD_INSTANCE":   3,
		"CLOUD_TASK":       4,
	}
)

func (x EResourceType) Enum() *EResourceType {
	p := new(EResourceType)
	*p = x
	return p
}

func (x EResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_resource_manager_proto_enumTypes[0].Descriptor()
}

func (EResourceType) Type() protoreflect.EnumType {
	return &file_api_proto_resource_manager_proto_enumTypes[0]
}

func (x EResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EResourceType.Descriptor instead.
func (EResourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{0}
}

type RMResponse_ResultCode int32

const (
	RMResponse_NONE      RMResponse_ResultCode = 0
	RMResponse_OK        RMResponse_ResultCode = 1
	RMResponse_NOT_FOUND RMResponse_ResultCode = 2
)

// Enum value maps for RMResponse_ResultCode.
var (
	RMResponse_ResultCode_name = map[int32]string{
		0: "NONE",
		1: "OK",
		2: "NOT_FOUND",
	}
	RMResponse_ResultCode_value = map[string]int32{
		"NONE":      0,
		"OK":        1,
		"NOT_FOUND": 2,
	}
)

func (x RMResponse_ResultCode) Enum() *RMResponse_ResultCode {
	p := new(RMResponse_ResultCode)
	*p = x
	return p
}

func (x RMResponse_ResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RMResponse_ResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_resource_manager_proto_enumTypes[1].Descriptor()
}

func (RMResponse_ResultCode) Type() protoreflect.EnumType {
	return &file_api_proto_resource_manager_proto_enumTypes[1]
}

func (x RMResponse_ResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RMResponse_ResultCode.Descriptor instead.
func (RMResponse_ResultCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{25, 0}
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                               // required
	ExecutionShellCommand    string `protobuf:"bytes,2,opt,name=execution_shell_command,json=executionShellCommand,proto3" json:"execution_shell_command,omitempty"`          // required
	RequirementsShellCommand string `protobuf:"bytes,3,opt,name=requirements_shell_command,json=requirementsShellCommand,proto3" json:"requirements_shell_command,omitempty"` // optional
	DockerImage              string `protobuf:"bytes,4,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`                                          //optional
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetExecutionShellCommand() string {
	if x != nil {
		return x.ExecutionShellCommand
	}
	return ""
}

func (x *Task) GetRequirementsShellCommand() string {
	if x != nil {
		return x.RequirementsShellCommand
	}
	return ""
}

func (x *Task) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

type Greetings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // required
}

func (x *Greetings) Reset() {
	*x = Greetings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greetings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greetings) ProtoMessage() {}

func (x *Greetings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greetings.ProtoReflect.Descriptor instead.
func (*Greetings) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{1}
}

func (x *Greetings) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GreetingsValidation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // required
}

func (x *GreetingsValidation) Reset() {
	*x = GreetingsValidation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingsValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingsValidation) ProtoMessage() {}

func (x *GreetingsValidation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingsValidation.ProtoReflect.Descriptor instead.
func (*GreetingsValidation) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GreetingsValidation) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type Permissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users  []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Groups []string `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{3}
}

func (x *Permissions) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Permissions) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                           // required
	Type               EResourceType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.EResourceType" json:"type,omitempty"`                                // required
	OwnerId            string        `protobuf:"bytes,3,opt,name=ownerId,proto3" json:"ownerId,omitempty"`                                                 // required
	Token              string        `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                                     // required
	Permissions        *Permissions  `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`                                         // required
	Name               string        `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`                                                       // required
	TotalResources     *HardwareData `protobuf:"bytes,7,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`             // optional
	AvailableResources *HardwareData `protobuf:"bytes,8,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"` // optional
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetType() EResourceType {
	if x != nil {
		return x.Type
	}
	return EResourceType_RESOURCE_UNKNOWN
}

func (x *Resource) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Resource) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Resource) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetTotalResources() *HardwareData {
	if x != nil {
		return x.TotalResources
	}
	return nil
}

func (x *Resource) GetAvailableResources() *HardwareData {
	if x != nil {
		return x.AvailableResources
	}
	return nil
}

type HardwareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HardwareRequest) Reset() {
	*x = HardwareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareRequest) ProtoMessage() {}

func (x *HardwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareRequest.ProtoReflect.Descriptor instead.
func (*HardwareRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{5}
}

type HardwareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalHardwareData *HardwareData `protobuf:"bytes,1,opt,name=total_hardware_data,json=totalHardwareData,proto3" json:"total_hardware_data,omitempty"`
	FreeHardwareData  *HardwareData `protobuf:"bytes,2,opt,name=free_hardware_data,json=freeHardwareData,proto3" json:"free_hardware_data,omitempty"`
}

func (x *HardwareResponse) Reset() {
	*x = HardwareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardwareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareResponse) ProtoMessage() {}

func (x *HardwareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareResponse.ProtoReflect.Descriptor instead.
func (*HardwareResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{6}
}

func (x *HardwareResponse) GetTotalHardwareData() *HardwareData {
	if x != nil {
		return x.TotalHardwareData
	}
	return nil
}

func (x *HardwareResponse) GetFreeHardwareData() *HardwareData {
	if x != nil {
		return x.FreeHardwareData
	}
	return nil
}

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // required
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{7}
}

func (x *TaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    string      `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // required
	Result    *Result     `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                        // required
	TaskFiles []*TaskFile `protobuf:"bytes,3,rep,name=task_files,json=taskFiles,proto3" json:"task_files,omitempty"` // required
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResponse) GetTaskFiles() []*TaskFile {
	if x != nil {
		return x.TaskFiles
	}
	return nil
}

type FileOnAgent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                           // required
	AgentRelativeLocalPath string `protobuf:"bytes,2,opt,name=agent_relative_local_path,json=agentRelativeLocalPath,proto3" json:"agent_relative_local_path,omitempty"` // required
	Hash                   string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`                                                                       // required
}

func (x *FileOnAgent) Reset() {
	*x = FileOnAgent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileOnAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOnAgent) ProtoMessage() {}

func (x *FileOnAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOnAgent.ProtoReflect.Descriptor instead.
func (*FileOnAgent) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{9}
}

func (x *FileOnAgent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileOnAgent) GetAgentRelativeLocalPath() string {
	if x != nil {
		return x.AgentRelativeLocalPath
	}
	return ""
}

func (x *FileOnAgent) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type StageInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string         `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
	Files  []*FileOnAgent `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *StageInRequest) Reset() {
	*x = StageInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageInRequest) ProtoMessage() {}

func (x *StageInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageInRequest.ProtoReflect.Descriptor instead.
func (*StageInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{10}
}

func (x *StageInRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StageInRequest) GetFiles() []*FileOnAgent {
	if x != nil {
		return x.Files
	}
	return nil
}

type StageInResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`               // required
}

func (x *StageInResponse) Reset() {
	*x = StageInResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageInResponse) ProtoMessage() {}

func (x *StageInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageInResponse.ProtoReflect.Descriptor instead.
func (*StageInResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{11}
}

func (x *StageInResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StageInResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type StageOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId                 string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                     // required
	AgentRelativeLocalPath string `protobuf:"bytes,2,opt,name=agent_relative_local_path,json=agentRelativeLocalPath,proto3" json:"agent_relative_local_path,omitempty"` // required
}

func (x *StageOutRequest) Reset() {
	*x = StageOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageOutRequest) ProtoMessage() {}

func (x *StageOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageOutRequest.ProtoReflect.Descriptor instead.
func (*StageOutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{12}
}

func (x *StageOutRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StageOutRequest) GetAgentRelativeLocalPath() string {
	if x != nil {
		return x.AgentRelativeLocalPath
	}
	return ""
}

type StageOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string       `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`       // required
	TaskFile *FileOnAgent `protobuf:"bytes,2,opt,name=task_file,json=taskFile,proto3" json:"task_file,omitempty"` // required
}

func (x *StageOutResponse) Reset() {
	*x = StageOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageOutResponse) ProtoMessage() {}

func (x *StageOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageOutResponse.ProtoReflect.Descriptor instead.
func (*StageOutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{13}
}

func (x *StageOutResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StageOutResponse) GetTaskFile() *FileOnAgent {
	if x != nil {
		return x.TaskFile
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // required
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CreateResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"` // required
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{16}
}

func (x *CreateResourceRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{17}
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // required
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // required
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *DeleteResourceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{19}
}

// FIXME(BigRedEye) ...
type ToAgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*ToAgentMessage_HardwareRequest
	//	*ToAgentMessage_TaskRequest
	//	*ToAgentMessage_StageInRequest
	//	*ToAgentMessage_StageOutRequest
	//	*ToAgentMessage_CancelTaskRequest
	//	*ToAgentMessage_DeleteTaskRequest
	//	*ToAgentMessage_GreetingsValidation
	Body isToAgentMessage_Body `protobuf_oneof:"Body"`
}

func (x *ToAgentMessage) Reset() {
	*x = ToAgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToAgentMessage) ProtoMessage() {}

func (x *ToAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToAgentMessage.ProtoReflect.Descriptor instead.
func (*ToAgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{20}
}

func (m *ToAgentMessage) GetBody() isToAgentMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ToAgentMessage) GetHardwareRequest() *HardwareRequest {
	if x, ok := x.GetBody().(*ToAgentMessage_HardwareRequest); ok {
		return x.HardwareRequest
	}
	return nil
}

func (x *ToAgentMessage) GetTaskRequest() *TaskRequest {
	if x, ok := x.GetBody().(*ToAgentMessage_TaskRequest); ok {
		return x.TaskRequest
	}
	return nil
}

func (x *ToAgentMessage) GetStageInRequest() *StageInRequest {
	if x, ok := x.GetBody().(*ToAgentMessage_StageInRequest); ok {
		return x.StageInRequest
	}
	return nil
}

func (x *ToAgentMessage) GetStageOutRequest() *StageOutRequest {
	if x, ok := x.GetBody().(*ToAgentMessage_StageOutRequest); ok {
		return x.StageOutRequest
	}
	return nil
}

func (x *ToAgentMessage) GetCancelTaskRequest() *CancelTaskRequest {
	if x, ok := x.GetBody().(*ToAgentMessage_CancelTaskRequest); ok {
		return x.CancelTaskRequest
	}
	return nil
}

func (x *ToAgentMessage) GetDeleteTaskRequest() *DeleteTaskRequest {
	if x, ok := x.GetBody().(*ToAgentMessage_DeleteTaskRequest); ok {
		return x.DeleteTaskRequest
	}
	return nil
}

func (x *ToAgentMessage) GetGreetingsValidation() *GreetingsValidation {
	if x, ok := x.GetBody().(*ToAgentMessage_GreetingsValidation); ok {
		return x.GreetingsValidation
	}
	return nil
}

type isToAgentMessage_Body interface {
	isToAgentMessage_Body()
}

type ToAgentMessage_HardwareRequest struct {
	HardwareRequest *HardwareRequest `protobuf:"bytes,1,opt,name=hardware_request,json=hardwareRequest,proto3,oneof"`
}

type ToAgentMessage_TaskRequest struct {
	TaskRequest *TaskRequest `protobuf:"bytes,2,opt,name=task_request,json=taskRequest,proto3,oneof"`
}

type ToAgentMessage_StageInRequest struct {
	StageInRequest *StageInRequest `protobuf:"bytes,3,opt,name=stage_in_request,json=stageInRequest,proto3,oneof"`
}

type ToAgentMessage_StageOutRequest struct {
	StageOutRequest *StageOutRequest `protobuf:"bytes,4,opt,name=stage_out_request,json=stageOutRequest,proto3,oneof"`
}

type ToAgentMessage_CancelTaskRequest struct {
	CancelTaskRequest *CancelTaskRequest `protobuf:"bytes,5,opt,name=cancel_task_request,json=cancelTaskRequest,proto3,oneof"`
}

type ToAgentMessage_DeleteTaskRequest struct {
	DeleteTaskRequest *DeleteTaskRequest `protobuf:"bytes,6,opt,name=delete_task_request,json=deleteTaskRequest,proto3,oneof"`
}

type ToAgentMessage_GreetingsValidation struct {
	GreetingsValidation *GreetingsValidation `protobuf:"bytes,7,opt,name=greetings_validation,json=greetingsValidation,proto3,oneof"`
}

func (*ToAgentMessage_HardwareRequest) isToAgentMessage_Body() {}

func (*ToAgentMessage_TaskRequest) isToAgentMessage_Body() {}

func (*ToAgentMessage_StageInRequest) isToAgentMessage_Body() {}

func (*ToAgentMessage_StageOutRequest) isToAgentMessage_Body() {}

func (*ToAgentMessage_CancelTaskRequest) isToAgentMessage_Body() {}

func (*ToAgentMessage_DeleteTaskRequest) isToAgentMessage_Body() {}

func (*ToAgentMessage_GreetingsValidation) isToAgentMessage_Body() {}

// FIXME(BigRedEye) .....
type FromAgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*FromAgentMessage_HardwareResponse
	//	*FromAgentMessage_Greetings
	//	*FromAgentMessage_TaskResponse
	//	*FromAgentMessage_StageInResponse
	//	*FromAgentMessage_StageOutResponse
	Body isFromAgentMessage_Body `protobuf_oneof:"Body"`
}

func (x *FromAgentMessage) Reset() {
	*x = FromAgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromAgentMessage) ProtoMessage() {}

func (x *FromAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromAgentMessage.ProtoReflect.Descriptor instead.
func (*FromAgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{21}
}

func (m *FromAgentMessage) GetBody() isFromAgentMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *FromAgentMessage) GetHardwareResponse() *HardwareResponse {
	if x, ok := x.GetBody().(*FromAgentMessage_HardwareResponse); ok {
		return x.HardwareResponse
	}
	return nil
}

func (x *FromAgentMessage) GetGreetings() *Greetings {
	if x, ok := x.GetBody().(*FromAgentMessage_Greetings); ok {
		return x.Greetings
	}
	return nil
}

func (x *FromAgentMessage) GetTaskResponse() *TaskResponse {
	if x, ok := x.GetBody().(*FromAgentMessage_TaskResponse); ok {
		return x.TaskResponse
	}
	return nil
}

func (x *FromAgentMessage) GetStageInResponse() *StageInResponse {
	if x, ok := x.GetBody().(*FromAgentMessage_StageInResponse); ok {
		return x.StageInResponse
	}
	return nil
}

func (x *FromAgentMessage) GetStageOutResponse() *StageOutResponse {
	if x, ok := x.GetBody().(*FromAgentMessage_StageOutResponse); ok {
		return x.StageOutResponse
	}
	return nil
}

type isFromAgentMessage_Body interface {
	isFromAgentMessage_Body()
}

type FromAgentMessage_HardwareResponse struct {
	HardwareResponse *HardwareResponse `protobuf:"bytes,1,opt,name=hardware_response,json=hardwareResponse,proto3,oneof"`
}

type FromAgentMessage_Greetings struct {
	Greetings *Greetings `protobuf:"bytes,2,opt,name=greetings,proto3,oneof"`
}

type FromAgentMessage_TaskResponse struct {
	TaskResponse *TaskResponse `protobuf:"bytes,3,opt,name=task_response,json=taskResponse,proto3,oneof"`
}

type FromAgentMessage_StageInResponse struct {
	StageInResponse *StageInResponse `protobuf:"bytes,4,opt,name=stage_in_response,json=stageInResponse,proto3,oneof"`
}

type FromAgentMessage_StageOutResponse struct {
	StageOutResponse *StageOutResponse `protobuf:"bytes,5,opt,name=stage_out_response,json=stageOutResponse,proto3,oneof"`
}

func (*FromAgentMessage_HardwareResponse) isFromAgentMessage_Body() {}

func (*FromAgentMessage_Greetings) isFromAgentMessage_Body() {}

func (*FromAgentMessage_TaskResponse) isFromAgentMessage_Body() {}

func (*FromAgentMessage_StageInResponse) isFromAgentMessage_Body() {}

func (*FromAgentMessage_StageOutResponse) isFromAgentMessage_Body() {}

// FIXME(BigRedEye) .......
type ResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*ResourceRequest_CreateResourceRequest
	//	*ResourceRequest_DeleteResourceRequest
	Body isResourceRequest_Body `protobuf_oneof:"Body"`
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{22}
}

func (m *ResourceRequest) GetBody() isResourceRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ResourceRequest) GetCreateResourceRequest() *CreateResourceRequest {
	if x, ok := x.GetBody().(*ResourceRequest_CreateResourceRequest); ok {
		return x.CreateResourceRequest
	}
	return nil
}

func (x *ResourceRequest) GetDeleteResourceRequest() *DeleteResourceRequest {
	if x, ok := x.GetBody().(*ResourceRequest_DeleteResourceRequest); ok {
		return x.DeleteResourceRequest
	}
	return nil
}

type isResourceRequest_Body interface {
	isResourceRequest_Body()
}

type ResourceRequest_CreateResourceRequest struct {
	CreateResourceRequest *CreateResourceRequest `protobuf:"bytes,1,opt,name=create_resource_request,json=createResourceRequest,proto3,oneof"`
}

type ResourceRequest_DeleteResourceRequest struct {
	DeleteResourceRequest *DeleteResourceRequest `protobuf:"bytes,2,opt,name=delete_resource_request,json=deleteResourceRequest,proto3,oneof"`
}

func (*ResourceRequest_CreateResourceRequest) isResourceRequest_Body() {}

func (*ResourceRequest_DeleteResourceRequest) isResourceRequest_Body() {}

// FIXME(BigRedEye) .........
type ResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*ResourceResponse_CreateResourceResponse
	//	*ResourceResponse_DeleteResourceResponse
	Body isResourceResponse_Body `protobuf_oneof:"Body"`
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{23}
}

func (m *ResourceResponse) GetBody() isResourceResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ResourceResponse) GetCreateResourceResponse() *CreateResourceResponse {
	if x, ok := x.GetBody().(*ResourceResponse_CreateResourceResponse); ok {
		return x.CreateResourceResponse
	}
	return nil
}

func (x *ResourceResponse) GetDeleteResourceResponse() *DeleteResourceResponse {
	if x, ok := x.GetBody().(*ResourceResponse_DeleteResourceResponse); ok {
		return x.DeleteResourceResponse
	}
	return nil
}

type isResourceResponse_Body interface {
	isResourceResponse_Body()
}

type ResourceResponse_CreateResourceResponse struct {
	CreateResourceResponse *CreateResourceResponse `protobuf:"bytes,1,opt,name=create_resource_response,json=createResourceResponse,proto3,oneof"`
}

type ResourceResponse_DeleteResourceResponse struct {
	DeleteResourceResponse *DeleteResourceResponse `protobuf:"bytes,2,opt,name=delete_resource_response,json=deleteResourceResponse,proto3,oneof"`
}

func (*ResourceResponse_CreateResourceResponse) isResourceResponse_Body() {}

func (*ResourceResponse_DeleteResourceResponse) isResourceResponse_Body() {}

type RMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId  string          `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`    // required
	RealMessage *ToAgentMessage `protobuf:"bytes,2,opt,name=real_message,json=realMessage,proto3" json:"real_message,omitempty"` //required
}

func (x *RMRequest) Reset() {
	*x = RMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMRequest) ProtoMessage() {}

func (x *RMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMRequest.ProtoReflect.Descriptor instead.
func (*RMRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{24}
}

func (x *RMRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *RMRequest) GetRealMessage() *ToAgentMessage {
	if x != nil {
		return x.RealMessage
	}
	return nil
}

// FIXME(BigRedEye) WTF?
type RMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode RMResponse_ResultCode `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=pb.RMResponse_ResultCode" json:"result_code,omitempty"` // required
}

func (x *RMResponse) Reset() {
	*x = RMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMResponse) ProtoMessage() {}

func (x *RMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMResponse.ProtoReflect.Descriptor instead.
func (*RMResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{25}
}

func (x *RMResponse) GetResultCode() RMResponse_ResultCode {
	if x != nil {
		return x.ResultCode
	}
	return RMResponse_NONE
}

type GetResourcesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requirements *HardwareData `protobuf:"bytes,1,opt,name=requirements,proto3" json:"requirements,omitempty"` // optional
	Limit        uint32        `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`              // optional
}

func (x *GetResourcesRequest) Reset() {
	*x = GetResourcesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcesRequest) ProtoMessage() {}

func (x *GetResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetResourcesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{26}
}

func (x *GetResourcesRequest) GetRequirements() *HardwareData {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *GetResourcesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetResourcesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []*Resource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *GetResourcesResponse) Reset() {
	*x = GetResourcesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resource_manager_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcesResponse) ProtoMessage() {}

func (x *GetResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resource_manager_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetResourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_resource_manager_proto_rawDescGZIP(), []int{27}
}

func (x *GetResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_api_proto_resource_manager_proto protoreflect.FileDescriptor

var file_api_proto_resource_manager_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x01, 0x0a, 0x04, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x68, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x15, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68,
	0x65, 0x6c, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3c, 0x0a, 0x1a, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x39,
	0x0a, 0x13, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3b, 0x0a, 0x0b, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0xb6, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x31, 0x0a, 0x0b, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x39, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0e, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x13,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x12, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22,
	0x11, 0x0a, 0x0f, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x94, 0x01, 0x0a, 0x10, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x48, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3e, 0x0a, 0x12, 0x66, 0x72, 0x65,
	0x65, 0x5f, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x10, 0x66, 0x72, 0x65, 0x65, 0x48, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x0b, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x78, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x22, 0x6c, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x39, 0x0a, 0x19, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x16, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x50,
	0x0a, 0x0e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4f, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x22, 0x4e, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x65, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x19,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x16, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x22, 0x59, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x4f, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x46, 0x69,
	0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x41,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x51, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x18,
	0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xf3, 0x03, 0x0a, 0x0e, 0x54, 0x6f, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x68,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x68, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a,
	0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6f, 0x75, 0x74,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x13, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x63, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x47, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x14, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x13, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0xd0,
	0x02, 0x0a, 0x10, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x11, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x00, 0x52, 0x09, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x37, 0x0a, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x41, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x12, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6f, 0x75, 0x74,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4f, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64,
	0x79, 0x22, 0xc3, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x17, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x15, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x17, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x15, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0xca, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x18,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x16, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x18, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x16, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x42, 0x6f, 0x64, 0x79, 0x22, 0x63, 0x0a, 0x09, 0x52, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x72, 0x65,
	0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x77, 0x0a, 0x0a, 0x52, 0x4d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x4b, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x02, 0x22, 0x61, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0c, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x42, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2a, 0x5f, 0x0a, 0x0d, 0x45, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45,
	0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x50, 0x4f, 0x4f, 0x4c, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x5f,
	0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4c,
	0x4f, 0x55, 0x44, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x10, 0x04, 0x32, 0x8e, 0x02, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x36,
	0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x6f, 0x6d,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a,
	0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x42, 0x21, 0x5a, 0x1f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x63, 0x2d, 0x6c, 0x61, 0x62,
	0x2f, 0x73, 0x6b, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_resource_manager_proto_rawDescOnce sync.Once
	file_api_proto_resource_manager_proto_rawDescData = file_api_proto_resource_manager_proto_rawDesc
)

func file_api_proto_resource_manager_proto_rawDescGZIP() []byte {
	file_api_proto_resource_manager_proto_rawDescOnce.Do(func() {
		file_api_proto_resource_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_resource_manager_proto_rawDescData)
	})
	return file_api_proto_resource_manager_proto_rawDescData
}

var file_api_proto_resource_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_resource_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_proto_resource_manager_proto_goTypes = []interface{}{
	(EResourceType)(0),             // 0: pb.EResourceType
	(RMResponse_ResultCode)(0),     // 1: pb.RMResponse.ResultCode
	(*Task)(nil),                   // 2: pb.Task
	(*Greetings)(nil),              // 3: pb.Greetings
	(*GreetingsValidation)(nil),    // 4: pb.GreetingsValidation
	(*Permissions)(nil),            // 5: pb.Permissions
	(*Resource)(nil),               // 6: pb.Resource
	(*HardwareRequest)(nil),        // 7: pb.HardwareRequest
	(*HardwareResponse)(nil),       // 8: pb.HardwareResponse
	(*TaskRequest)(nil),            // 9: pb.TaskRequest
	(*TaskResponse)(nil),           // 10: pb.TaskResponse
	(*FileOnAgent)(nil),            // 11: pb.FileOnAgent
	(*StageInRequest)(nil),         // 12: pb.StageInRequest
	(*StageInResponse)(nil),        // 13: pb.StageInResponse
	(*StageOutRequest)(nil),        // 14: pb.StageOutRequest
	(*StageOutResponse)(nil),       // 15: pb.StageOutResponse
	(*CancelTaskRequest)(nil),      // 16: pb.CancelTaskRequest
	(*DeleteTaskRequest)(nil),      // 17: pb.DeleteTaskRequest
	(*CreateResourceRequest)(nil),  // 18: pb.CreateResourceRequest
	(*CreateResourceResponse)(nil), // 19: pb.CreateResourceResponse
	(*DeleteResourceRequest)(nil),  // 20: pb.DeleteResourceRequest
	(*DeleteResourceResponse)(nil), // 21: pb.DeleteResourceResponse
	(*ToAgentMessage)(nil),         // 22: pb.ToAgentMessage
	(*FromAgentMessage)(nil),       // 23: pb.FromAgentMessage
	(*ResourceRequest)(nil),        // 24: pb.ResourceRequest
	(*ResourceResponse)(nil),       // 25: pb.ResourceResponse
	(*RMRequest)(nil),              // 26: pb.RMRequest
	(*RMResponse)(nil),             // 27: pb.RMResponse
	(*GetResourcesRequest)(nil),    // 28: pb.GetResourcesRequest
	(*GetResourcesResponse)(nil),   // 29: pb.GetResourcesResponse
	(*Result)(nil),                 // 30: pb.Result
	(*HardwareData)(nil),           // 31: pb.HardwareData
	(*TaskFile)(nil),               // 32: pb.TaskFile
}
var file_api_proto_resource_manager_proto_depIdxs = []int32{
	30, // 0: pb.GreetingsValidation.result:type_name -> pb.Result
	0,  // 1: pb.Resource.type:type_name -> pb.EResourceType
	5,  // 2: pb.Resource.permissions:type_name -> pb.Permissions
	31, // 3: pb.Resource.total_resources:type_name -> pb.HardwareData
	31, // 4: pb.Resource.available_resources:type_name -> pb.HardwareData
	31, // 5: pb.HardwareResponse.total_hardware_data:type_name -> pb.HardwareData
	31, // 6: pb.HardwareResponse.free_hardware_data:type_name -> pb.HardwareData
	2,  // 7: pb.TaskRequest.task:type_name -> pb.Task
	30, // 8: pb.TaskResponse.result:type_name -> pb.Result
	32, // 9: pb.TaskResponse.task_files:type_name -> pb.TaskFile
	11, // 10: pb.StageInRequest.files:type_name -> pb.FileOnAgent
	30, // 11: pb.StageInResponse.result:type_name -> pb.Result
	11, // 12: pb.StageOutResponse.task_file:type_name -> pb.FileOnAgent
	6,  // 13: pb.CreateResourceRequest.resource:type_name -> pb.Resource
	7,  // 14: pb.ToAgentMessage.hardware_request:type_name -> pb.HardwareRequest
	9,  // 15: pb.ToAgentMessage.task_request:type_name -> pb.TaskRequest
	12, // 16: pb.ToAgentMessage.stage_in_request:type_name -> pb.StageInRequest
	14, // 17: pb.ToAgentMessage.stage_out_request:type_name -> pb.StageOutRequest
	16, // 18: pb.ToAgentMessage.cancel_task_request:type_name -> pb.CancelTaskRequest
	17, // 19: pb.ToAgentMessage.delete_task_request:type_name -> pb.DeleteTaskRequest
	4,  // 20: pb.ToAgentMessage.greetings_validation:type_name -> pb.GreetingsValidation
	8,  // 21: pb.FromAgentMessage.hardware_response:type_name -> pb.HardwareResponse
	3,  // 22: pb.FromAgentMessage.greetings:type_name -> pb.Greetings
	10, // 23: pb.FromAgentMessage.task_response:type_name -> pb.TaskResponse
	13, // 24: pb.FromAgentMessage.stage_in_response:type_name -> pb.StageInResponse
	15, // 25: pb.FromAgentMessage.stage_out_response:type_name -> pb.StageOutResponse
	18, // 26: pb.ResourceRequest.create_resource_request:type_name -> pb.CreateResourceRequest
	20, // 27: pb.ResourceRequest.delete_resource_request:type_name -> pb.DeleteResourceRequest
	19, // 28: pb.ResourceResponse.create_resource_response:type_name -> pb.CreateResourceResponse
	21, // 29: pb.ResourceResponse.delete_resource_response:type_name -> pb.DeleteResourceResponse
	22, // 30: pb.RMRequest.real_message:type_name -> pb.ToAgentMessage
	1,  // 31: pb.RMResponse.result_code:type_name -> pb.RMResponse.ResultCode
	31, // 32: pb.GetResourcesRequest.requirements:type_name -> pb.HardwareData
	6,  // 33: pb.GetResourcesResponse.resources:type_name -> pb.Resource
	23, // 34: pb.ResourceManager.Send:input_type -> pb.FromAgentMessage
	24, // 35: pb.ResourceManager.Update:input_type -> pb.ResourceRequest
	26, // 36: pb.ResourceManager.AgentAction:input_type -> pb.RMRequest
	28, // 37: pb.ResourceManager.GetResources:input_type -> pb.GetResourcesRequest
	22, // 38: pb.ResourceManager.Send:output_type -> pb.ToAgentMessage
	25, // 39: pb.ResourceManager.Update:output_type -> pb.ResourceResponse
	27, // 40: pb.ResourceManager.AgentAction:output_type -> pb.RMResponse
	29, // 41: pb.ResourceManager.GetResources:output_type -> pb.GetResourcesResponse
	38, // [38:42] is the sub-list for method output_type
	34, // [34:38] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_api_proto_resource_manager_proto_init() }
func file_api_proto_resource_manager_proto_init() {
	if File_api_proto_resource_manager_proto != nil {
		return
	}
	file_api_proto_action_proto_init()
	file_api_proto_hardware_data_proto_init()
	file_api_proto_task_results_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_proto_resource_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greetings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetingsValidation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardwareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileOnAgent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageInResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToAgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromAgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourcesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resource_manager_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResourcesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_resource_manager_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*ToAgentMessage_HardwareRequest)(nil),
		(*ToAgentMessage_TaskRequest)(nil),
		(*ToAgentMessage_StageInRequest)(nil),
		(*ToAgentMessage_StageOutRequest)(nil),
		(*ToAgentMessage_CancelTaskRequest)(nil),
		(*ToAgentMessage_DeleteTaskRequest)(nil),
		(*ToAgentMessage_GreetingsValidation)(nil),
	}
	file_api_proto_resource_manager_proto_msgTypes[21].OneofWrappers = []interface{}{
		(*FromAgentMessage_HardwareResponse)(nil),
		(*FromAgentMessage_Greetings)(nil),
		(*FromAgentMessage_TaskResponse)(nil),
		(*FromAgentMessage_StageInResponse)(nil),
		(*FromAgentMessage_StageOutResponse)(nil),
	}
	file_api_proto_resource_manager_proto_msgTypes[22].OneofWrappers = []interface{}{
		(*ResourceRequest_CreateResourceRequest)(nil),
		(*ResourceRequest_DeleteResourceRequest)(nil),
	}
	file_api_proto_resource_manager_proto_msgTypes[23].OneofWrappers = []interface{}{
		(*ResourceResponse_CreateResourceResponse)(nil),
		(*ResourceResponse_DeleteResourceResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_resource_manager_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_resource_manager_proto_goTypes,
		DependencyIndexes: file_api_proto_resource_manager_proto_depIdxs,
		EnumInfos:         file_api_proto_resource_manager_proto_enumTypes,
		MessageInfos:      file_api_proto_resource_manager_proto_msgTypes,
	}.Build()
	File_api_proto_resource_manager_proto = out.File
	file_api_proto_resource_manager_proto_rawDesc = nil
	file_api_proto_resource_manager_proto_goTypes = nil
	file_api_proto_resource_manager_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceManagerClient is the client API for ResourceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceManagerClient interface {
	Send(ctx context.Context, opts ...grpc.CallOption) (ResourceManager_SendClient, error)
	Update(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	AgentAction(ctx context.Context, in *RMRequest, opts ...grpc.CallOption) (*RMResponse, error)
	GetResources(ctx context.Context, in *GetResourcesRequest, opts ...grpc.CallOption) (*GetResourcesResponse, error)
}

type resourceManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceManagerClient(cc grpc.ClientConnInterface) ResourceManagerClient {
	return &resourceManagerClient{cc}
}

func (c *resourceManagerClient) Send(ctx context.Context, opts ...grpc.CallOption) (ResourceManager_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ResourceManager_serviceDesc.Streams[0], "/pb.ResourceManager/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceManagerSendClient{stream}
	return x, nil
}

type ResourceManager_SendClient interface {
	Send(*FromAgentMessage) error
	Recv() (*ToAgentMessage, error)
	grpc.ClientStream
}

type resourceManagerSendClient struct {
	grpc.ClientStream
}

func (x *resourceManagerSendClient) Send(m *FromAgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resourceManagerSendClient) Recv() (*ToAgentMessage, error) {
	m := new(ToAgentMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resourceManagerClient) Update(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, "/pb.ResourceManager/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerClient) AgentAction(ctx context.Context, in *RMRequest, opts ...grpc.CallOption) (*RMResponse, error) {
	out := new(RMResponse)
	err := c.cc.Invoke(ctx, "/pb.ResourceManager/AgentAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerClient) GetResources(ctx context.Context, in *GetResourcesRequest, opts ...grpc.CallOption) (*GetResourcesResponse, error) {
	out := new(GetResourcesResponse)
	err := c.cc.Invoke(ctx, "/pb.ResourceManager/GetResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceManagerServer is the server API for ResourceManager service.
type ResourceManagerServer interface {
	Send(ResourceManager_SendServer) error
	Update(context.Context, *ResourceRequest) (*ResourceResponse, error)
	AgentAction(context.Context, *RMRequest) (*RMResponse, error)
	GetResources(context.Context, *GetResourcesRequest) (*GetResourcesResponse, error)
}

// UnimplementedResourceManagerServer can be embedded to have forward compatible implementations.
type UnimplementedResourceManagerServer struct {
}

func (*UnimplementedResourceManagerServer) Send(ResourceManager_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedResourceManagerServer) Update(context.Context, *ResourceRequest) (*ResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedResourceManagerServer) AgentAction(context.Context, *RMRequest) (*RMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentAction not implemented")
}
func (*UnimplementedResourceManagerServer) GetResources(context.Context, *GetResourcesRequest) (*GetResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResources not implemented")
}

func RegisterResourceManagerServer(s *grpc.Server, srv ResourceManagerServer) {
	s.RegisterService(&_ResourceManager_serviceDesc, srv)
}

func _ResourceManager_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResourceManagerServer).Send(&resourceManagerSendServer{stream})
}

type ResourceManager_SendServer interface {
	Send(*ToAgentMessage) error
	Recv() (*FromAgentMessage, error)
	grpc.ServerStream
}

type resourceManagerSendServer struct {
	grpc.ServerStream
}

func (x *resourceManagerSendServer) Send(m *ToAgentMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resourceManagerSendServer) Recv() (*FromAgentMessage, error) {
	m := new(FromAgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ResourceManager_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceManager/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServer).Update(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManager_AgentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServer).AgentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceManager/AgentAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServer).AgentAction(ctx, req.(*RMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManager_GetResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServer).GetResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceManager/GetResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServer).GetResources(ctx, req.(*GetResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ResourceManager",
	HandlerType: (*ResourceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _ResourceManager_Update_Handler,
		},
		{
			MethodName: "AgentAction",
			Handler:    _ResourceManager_AgentAction_Handler,
		},
		{
			MethodName: "GetResources",
			Handler:    _ResourceManager_GetResources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _ResourceManager_Send_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/resource_manager.proto",
}
