version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
    volumes:
      - "/mnt/ssd1tb/sky-dm/postgres:/var/lib/postgresql/data"
    restart: always

  app:
    build: .
    ports:
      - 12913:8080
    environment:
      DM_BIND_ADDRES: ":8080"
      DM_POSTGRES_ADDRESS: "host=db port=5432 user=postgres password=DB_PASSWORD dbname=postgres sslmode=disable"
      DM_LOG_FILE: "/dev/null"
      DM_STORAGE_DIR: "/var/lib/data_manager/storage"
      DM_MAX_FILE_SIZE: "1073741824"
    depends_on:
      - db
    volumes:
      - "/mnt/ssd1tb/sky-dm/storage:/var/lib/data_manager/storage"
    restart: always
